build:
  steps:
    - pip install -r requirements.txt
    
services:
  - type: web
    name: ml-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: FLASK_ENV
        value: production