services:
  - type: web
    name: After-Dafter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        value: 997a1db4ccaf740955fda85838e0f88bcf87ff061260d41b84394bebbd3a5aeb
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
